name: Docker Build and Release
on: [ push ]
env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tipp: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  GITHUB_ACCESSTOKEN: ${{ secrets.MY_SECRET }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
  
    - name: Compile, build and push
      run: |
        #### AUFGABE COMPILE, DOCKER BUILD UND PUSH
          # hier ist Platz für maven package und docker build
          mvn package
          docker build --tag ghcr.io/alessaha/pet-clinic:latest -f Dockerfile .
          docker login --username alessaha --password $MY_SECRET ghcr.io
          docker push ghcr.io/alessaha/pet-clinic:latest
